services:

  db:
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - explorer-networks

  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/src/app
    ports:
      - "3333:3333"
    depends_on:
      - db
    command: ["sh", "/src/app/bin/sh/start.sh"]
    networks:
      - explorer-networks

volumes:
  pgdata:

networks:
  explorer-networks:
    driver: bridge