
services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - explorer-networks
  
  pg:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/src/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    command: ["npm", "start"]
    networks:
      - explorer-networks

volumes:
  pgdata:

networks:
  explorer-networks:
    driver: bridge