version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - app-data:/src/app/database
    ports:
      - "3000:3000"
    command: ["sh", "/src/app/bin/sh/start.sh"]

volumes:
  app-data: