import { BsFillHexagonFill } from "react-icons/bs";
import { Suspense } from "react";
import dynamic from "next/dynamic";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Login | Food explorer",
    description: "Generated by create next app",
  };

const HandleWithLogin = dynamic(() => 
    import(
        /* webpackChunkName: "handleWith-Login"*/
        '../../components/login/handleWithLogin'), { ssr: false }
)

export default function LogIn() {
    return (
        <section className="flex w-full min-h-screen m-0 flex-col px-8 pt-[98px] lg:pt-24 bg-dark-700 text-white lg:px-[108px] overflow-y-hidden lg:overflow-y-auto overscroll-x-none">
            <div className="flex flex-col w-full m-auto md:w-full lg:flex-row lg:justify-between max-w-[1368px]">
                <span className="flex w-full items-center justify-center lg:justify-start lg:items-start lg:mt-[200px] font-bold gap-2 text-3xl">
                    <span className="text-tint-cake-400 text-4xl"><BsFillHexagonFill /></span>
                    food explorer
                </span>

                <div className="flex flex-col w-full m-auto min-h-full gap-8  rounded-2xl lg:bg-dark-400 lg:p-16 max-w-[476px]">
                    <Suspense fallback={<div>Loading...</div>}>
                        <HandleWithLogin />
                    </Suspense>
                </div>
            </div>
        </section>
    )
}