import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400"], variable: '--font-roboto' })
const poppins = Poppins({ subsets: ["latin"], weight: ["300", "400"], variable: '--font-poppins' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${poppins.variable}`}>{children}</body>
    </html>
  );
}
