import { Metadata } from "next";


export const metadata: Metadata = {
    title: "Home | Food explorer",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="pt-BR">
        <body>
          {children}
        </body>
      </html>
    );
  }